### ISSUE TITLE
Expose max_iter of GMRES

### ISSUE THREAD

**Issue by BabaYara** [wagenaartje/torch-cgd#1]
In my application, I needed atleast 10000 interactions of GMRES to get convergence. 
It will therefore be useful to expose this in the solver interface.
Thanks a lot for the awesome work.
Any thoughts on writing one in Jax? 

Best, 
Fahiz

**Comment by wagenaartje** [comment]
Thank you for the kind words! I have updated the package, `max_iter` should now be exposed. You can check this in the updated [readme](https://github.com/wagenaartje/torch-cgd#choosing-the-right-solver). Unfortunately I am not familiar with Jax, so writing a Jax implementation is (currently) not planned. If you think of any other enhacements or encounter any bugs, feel free to create another issue.
